# Version de l'API Docker Compose à utiliser pour lire ce fichier
version: '3.8'

# Déclaration des services
services:

  # Un service nommée my_app
  my_app:

    # Définition du Dockerfile à build et à utiliser
    build:
      context: .
      dockerfile: Dockerfile

    # Configuration des ports à exposer sur le réseau
    expose:
      - '3000'

    # Nombre de réplicas souhaités du même container 
    deploy:
      replicas: 4 # Ici on déploie 4 fois le container au sein du service my_app
    
    environment:
      - PING_LISTEN_PORT=3000
    
    # Rédemarrage automatique dans tous les cas lorsqu'un container s'arrête
    restart: always

  # Un service nommé proxy
  proxy:

    # L'image Docker a utilisé pour le service
    image: nginx:latest

    # Monter un fichier du répertoire courant de l'hôte
    # sur le service
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    expose:
      - '80'
    
    # Configurer le port-forwarding entre l'hôte et le service
    ports:
      - 8080:80

    # Définir une relation de dépendance
    # Si my_app n'est pas prêt alors pas de proxy
    depends_on: 
      - my_app